const keys = [
  {
    classList: 'key character backquote ',
    ru: 'ё',
    ruShift: 'Ё',
    en: '`',
    enShift: '~',
  },
  {
    classList: 'key character number digit1',
    ru: '1',
    ruShift: '!',
    en: '1',
    enShift: '!',
  },
  {
    classList: 'key character number digit2',
    ru: '2',
    ruShift: '"',
    en: '2',
    enShift: '@',
  },
  {
    classList: 'key character number digit3',
    ru: '3',
    ruShift: '№',
    en: '3',
    enShift: '#',
  },
  {
    classList: 'key character number digit4',
    ru: '4',
    ruShift: ';',
    en: '4',
    enShift: '$',
  },
  {
    classList: 'key character number digit5',
    ru: '5',
    ruShift: '%',
    en: '5',
    enShift: '%',
  },
  {
    classList: 'key character number digit6',
    ru: '6',
    ruShift: ':',
    en: '6',
    enShift: '^',
  },
  {
    classList: 'key character number digit7',
    ru: '7',
    ruShift: '?',
    en: '7',
    enShift: '&',
  },
  {
    classList: 'key character number digit8',
    ru: '8',
    ruShift: '*',
    en: '8',
    enShift: '*',
  },
  {
    classList: 'key character number digit9',
    ru: '9',
    ruShift: '(',
    en: '9',
    enShift: '(',
  },
  {
    classList: 'key character number digit0',
    ru: '0',
    ruShift: ')',
    en: '0',
    enShift: ')',
  },
  {
    classList: 'key character minus numpadsubtract',
    ru: '-',
    ruShift: '_',
    en: '-',
    enShift: '_',
  },
  {
    classList: 'key character equal',
    ru: '=',
    ruShift: '+',
    en: '=',
    enShift: '+',
  },
  {
    classList: 'key backspace',
    ru: '&#8701;',
    ruShift: '&#8701;',
    en: '&#8701;',
    enShift: '&#8701;',
  },
  {
    classList: 'key tab',
    ru: '&#8633;',
    ruShift: '&#8633;',
    en: '&#8633;',
    enShift: '&#8633;',
  },
  {
    classList: 'key character keyq',
    ru: 'й',
    ruShift: 'Й',
    en: 'q',
    enShift: 'Q',
  },
  {
    classList: 'key character keyw',
    ru: 'ц',
    ruShift: 'Ц',
    en: 'w',
    enShift: 'W',
  },
  {
    classList: 'key character  keye',
    ru: 'у',
    ruShift: 'У',
    en: 'e',
    enShift: 'E',
  },
  {
    classList: 'key character  keyr',
    ru: 'к',
    ruShift: 'К',
    en: 'r',
    enShift: 'R',
  },
  {
    classList: 'key character  keyt',
    ru: 'е',
    ruShift: 'Е',
    en: 't',
    enShift: 'T',
  },
  {
    classList: 'key character  keyy',
    ru: 'н',
    ruShift: 'Н',
    en: 'y',
    enShift: 'Y',
  },
  {
    classList: 'key character keyu',
    ru: 'г',
    ruShift: 'Г',
    en: 'u',
    enShift: 'U',
  },
  {
    classList: 'key character  keyi',
    ru: 'ш',
    ruShift: 'Ш',
    en: 'i',
    enShift: 'I',
  },
  {
    classList: 'key character keyo',
    ru: 'щ',
    ruShift: 'Щ',
    en: 'o',
    enShift: 'O',
  },
  {
    classList: 'key character keyp',
    ru: 'з',
    ruShift: 'З',
    en: 'p',
    enShift: 'P',
  },
  {
    classList: 'key character open-bracket bracketleft',
    ru: 'х',
    ruShift: 'Х',
    en: '[',
    enShift: '{',
  },
  {
    classList: 'key character close-bracket bracketright',
    ru: 'ъ',
    ruShift: 'Ъ',
    en: ']',
    enShift: '}',
  },
  {
    classList: 'key enter',
    ru: '&#8629;',
    ruShift: '&#8629;',
    en: '&#8629;',
    enShift: '&#8629;',
  },
  {
    classList: 'key caps capslock',
    ru: '&#8659;',
    ruShift: '&#8659;',
    en: '&#8659;',
    enShift: '&#8659;',
  },
  {
    classList: 'key character keya',
    ru: 'ф',
    ruShift: 'Ф',
    en: 'a',
    enShift: 'A',
  },
  {
    classList: 'key character keys',
    ru: 'ы',
    ruShift: 'Ы',
    en: 's',
    enShift: 'S',
  },
  {
    classList: 'key character keyd',
    ru: 'в',
    ruShift: 'В',
    en: 'd',
    enShift: 'D',
  },
  {
    classList: 'key character keyf',
    ru: 'а',
    ruShift: 'А',
    en: 'f',
    enShift: 'F',
  },
  {
    classList: 'key character keyg',
    ru: 'п',
    ruShift: 'П',
    en: 'g',
    enShift: 'G',
  },
  {
    classList: 'key character keyh',
    ru: 'р',
    ruShift: 'Р',
    en: 'h',
    enShift: 'H',
  },
  {
    classList: 'key character keyj',
    ru: 'о',
    ruShift: 'О',
    en: 'j',
    enShift: 'J',
  },
  {
    classList: 'key character keyk',
    ru: 'л',
    ruShift: 'Л',
    en: 'k',
    enShift: 'K',
  },
  {
    classList: 'key character keyl',
    ru: 'д',
    ruShift: 'Д',
    en: 'l',
    enShift: 'L',
  },
  {
    classList: 'key character semicolon',
    ru: 'ж',
    ruShift: 'Ж',
    en: ';',
    enShift: ':',
  },
  {
    classList: 'key character apostrophe quote',
    ru: 'э',
    ruShift: 'Э',
    en: "'",
    enShift: '"',
  },
  {
    classList: 'key character backslash',
    ru: '\\',
    ruShift: '//',
    en: '\\',
    enShift: '|',
  },
  {
    classList: 'key shift left-shift shiftleft',
    ru: '&#8657;',
    ruShift: '&#8657;',
    en: '&#8657;',
    enShift: '&#8657;',
  },
  {
    classList: 'key character keyz',
    ru: 'я',
    ruShift: 'Я',
    en: 'z',
    enShift: 'Z',
  },
  {
    classList: 'key character keyx',
    ru: 'ч',
    ruShift: 'Ч',
    en: 'x',
    enShift: 'X',
  },
  {
    classList: 'key character keyc',
    ru: 'с',
    ruShift: 'С',
    en: 'c',
    enShift: 'C',
  },
  {
    classList: 'key character keyv',
    ru: 'м',
    ruShift: 'М',
    en: 'v',
    enShift: 'V',
  },
  {
    classList: 'key character keyb',
    ru: 'и',
    ruShift: 'И',
    en: 'b',
    enShift: 'B',
  },
  {
    classList: 'key character keyn',
    ru: 'т',
    ruShift: 'Т',
    en: 'n',
    enShift: 'N',
  },
  {
    classList: 'key character keym',
    ru: 'ь',
    ruShift: 'Ь',
    en: 'm',
    enShift: 'M',
  },
  {
    classList: 'key character comma numpaddecimal',
    ru: 'б',
    ruShift: 'Б',
    en: ',',
    enShift: '<',
  },
  {
    classList: 'key character dot period',
    ru: 'ю',
    ruShift: 'Ю',
    en: '.',
    enShift: '>',
  },
  {
    classList: 'key character forward-slash slash',
    ru: '.',
    ruShift: ',',
    en: '/',
    enShift: '?',
  },
  {
    classList: 'key arrow-up arrowup character',
    ru: '&#9651;',
    ruShift: '&#9651;',
    en: '&#9651;',
    enShift: '&#9651;',
  },
  {
    classList: 'key shift right-shift shiftright',
    ru: '&#8657;',
    ruShift: '&#8657;',
    en: '&#8657;',
    enShift: '&#8657;',
  },
  {
    classList: 'key ctrl right-ctrl controlleft',
    ru: 'ctrl',
    ruShift: 'ctrl',
    en: 'ctrl',
    enShift: 'ctrl',
  },
  {
    classList: 'key lang-change',
    ru: 'en',
    ruShift: 'en',
    en: 'ru',
    enShift: 'ru',
  },
  {
    classList: 'key alt left-alt altleft',
    ru: 'alt',
    ruShift: 'alt',
    en: 'alt',
    enShift: 'alt',
  },
  {
    classList: 'key character spacebar space',
    ru: ' ',
    ruShift: ' ',
    en: ' ',
    enShift: ' ',
  },
  {
    classList: 'key alt right-alt altright',
    ru: 'alt',
    ruShift: 'alt',
    en: 'alt',
    enShift: 'alt',
  },
  {
    classList: 'key ctrl right-ctrl controlright',
    ru: 'ctrl',
    ruShift: 'ctrl',
    en: 'ctrl',
    enShift: 'ctrl',
  },
  {
    classList: 'key arrow arrow-left arrowleft character',
    ru: '&#9665;',
    ruShift: '&#9665;',
    en: '&#9665;',
    enShift: '&#9665;',
  },
  {
    classList: 'key arrow arrow-bottom arrowdown character',
    ru: '&#9661;',
    ruShift: '&#9661;',
    en: '&#9661;',
    enShift: '&#9661;',
  },
  {
    classList: 'key arrow arrow-right arrowright character',
    ru: '&#9655;',
    ruShift: '&#9655;',
    en: '&#9655;',
    enShift: '&#9655;',
  },
  {
    classList: 'key del numpaddecimal',
    ru: 'del',
    ruShift: 'del',
    en: 'del',
    enShift: 'del',
  },
];

export default keys;
